# This is a docker compose file for defining and running
# multi-container environments. It simplifies the control
# of your application stack into a single configuration
# file. The following commands are useful:
#
#   docker compose up          - "runs" the entire system
#   docker compose up --build  - force a build and "runs" system
#   docker compose up -d       - "runs" system in detacted mode
#   docker compose down        - "closes" the entire system and deletes everything
#   docker compose stop        - stop running containers without removing them
#   docker compose start       - start previously stopped containers
#
version: '3.9'
name: cs426-project

services:
  registry:
    build:
      context: ./registry
    container_name: registry
    networks:
      - skynet

  market-service:
    build:
      context: ./market-service
    container_name: market-service
    depends_on:
      - registry
    networks:
      - skynet

  calculation-service:
    build:
      context: ./calculation-service
    container_name: calculation-service
    depends_on:
      - registry
    networks:
      - skynet

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    depends_on:
      - market-service
    networks:
      - skynet
    ports:
      - "3000:3000"
  database-service:
      build:
        context: ./database-service
      container_name: database-service
      depends_on:
        - registry
        - calculation-service
      networks:
        - skynet
      ports:
        - "3001:3001"
      environment:
        - PGHOST=aws-0-us-east-2.pooler.supabase.com
        - PGPORT=5432
        - PGUSER=postgres.rwwjgkpunukjdcjhojkc  # this part includes your project ref
        - PGPASSWORD=QpcpWWxCTDTvv9tv           # replace with your actual password
        - PGDATABASE=postgres
        - PGSSLMODE=require

  # database-service:
  #   build:
  #     context: ./database-service
  #   container_name: database-service
  #   depends_on:
  #     - registry
  #     - calculation-service
  #   networks:
  #     - skynet
  #   ports:
  #     - "3001:3001"
  #   dns:
  #     - 8.8.8.8
  #   environment:
  #     - PGHOST=db.rwwjgkpunukjdcjhojkc.supabase.co
  #     - PGPORT=5432
  #     - PGUSER=postgres
  #     - PGPASSWORD=QpcpWWxCTDTvv9tv
  #     - PGDATABASE=postgres
  #     - PGSSLMODE=require
  #     - NODE_OPTIONS=--dns-result-order=ipv4first
    



networks:
  skynet:
    driver: bridge

